# Generated by Django 4.2.2 on 2023-09-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_project_user_alter_todos_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('in progress', 'IN PROGRESS'), ('completed', 'COMPLETED'), ('under review', 'UNDER REVIEW'), ('on hold', 'ON HOLD')], default='in progress', max_length=30),
        ),
    ]
