# Generated by Django 4.2.2 on 2023-09-19 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_employee_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='permission',
            new_name='name',
        ),
    ]
