# Generated by Django 4.2.2 on 2023-06-25 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_todos'),
    ]

    operations = [
        migrations.AddField(
            model_name='todos',
            name='project',
            field=models.ForeignKey(default='jira clone', on_delete=django.db.models.deletion.CASCADE, to='api.project'),
        ),
    ]
