# Generated by Django 4.2.2 on 2023-09-05 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_custompermission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomPermission',
        ),
    ]
