# Generated by Django 4.2.5 on 2023-10-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_leave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='date_from',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='leave',
            name='date_to',
            field=models.DateTimeField(),
        ),
    ]
