# Generated by Django 4.2.2 on 2023-10-24 09:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_leave_date_from_alter_leave_date_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='project',
            name='name',
        ),
        migrations.AddField(
            model_name='project',
            name='client_name',
            field=models.CharField(default='Micheal Gundo', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(default='This is a Risk Management application', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.CharField(default='High', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='project_leader',
            field=models.CharField(default='Opiyo Samwel', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='project_name',
            field=models.CharField(default='RiskSolve', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
