# Generated by Django 4.2.2 on 2023-09-05 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todos',
        ),
    ]
