# Generated by Django 4.2.2 on 2023-09-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_delete_todos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('in progress', 'IN PROGRESS'), ('completed', 'COMPLETED'), ('under review', 'UNDER REVIEW'), ('on hold', 'ON HOLD')], default='in progress', max_length=30)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
