# Generated by Django 4.2.2 on 2023-09-08 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_user_roles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='name',
            new_name='permission',
        ),
    ]
